### ISSUE TITLE
5.4+ Not existing function in example

### ISSUE THREAD

**Issue by xXSchrandXx** [WoltLab/woltlab.github.io#329] opened 2022-10-29 07:19 UTC
In these [Examples](https://docs.woltlab.com/5.4/php/api/form_builder/dependencies/#examples) are functions `values` and `negate` used. But they don't exists in [NonEmptyFormFieldDependency](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/form/builder/field/dependency/NonEmptyFormFieldDependency.class.php).

**Comment by TimWolla** [comment] 2022-10-31 09:20
The issue is not that the methods do not exist, the wrong class is used in the example. Now fixed, thanks!

**Closed as completed** 2022-10-31 09:25 UTC
